synapse = "https://matrix.familyhainz.de"
forgejo = "https://gitea.familyhainz.de"
nextcloud = "https://nextcloud.mymiggi.de"
keycloak = "https://auth.familyhainz.de"
portainer = "https://vmd116727.contaboserver.net"