synapse = "https://matrix.familyhainz.de"
forgejo = "https://gitea.familyhainz.de"
nextcloud = "https://nextcloud.mymiggi.de"
keycloak = "https://auth.familyhainz.de"
portainer = "https://vmd116727.contaboserver.net"
bitwarden = "https://bitwarden.familyhainz.de"
wordpress = "https://www.mymiggi.de"
gotosocial = "https://social.mymiggi.de"
#
room-id = "!hFekksusgjPusUvBbO:matrix.familyhainz.de"

[notifications]
gotosocial_token = "ZGEZYZNMODYTNMRMNS0ZYJAXLTG3ZDUTNZIXYZQ0MTZJZMZH"
gotosocial_enable = true