synapse = "https://matrix.example.com"
forgejo = "https://forgejo.example.com"
nextcloud = "https://nextcloud.example.com
keycloak = "https://keycloak.example.com"
portainer = "https://portainer.example.com"
bitwarden = "https://bitwarden.example.com"
wordpress = "https://www.example.com
#
room-id = "!xxxxxxxxxxxxxxxxxx:matrix.example.com"