version: '3.3'
services:
  miggi:
    container_name: ghost
    image: gitea.familyhainz.de/miggi/matrix-ghost-bot:amd64 #arm-v7 For RaspberryPi
    restart: always
    environment:
      - 'URL=https://matrix.example.com'
      - 'USR=@ghost:matrix.example.com'
      - 'PW=VERY_SECURE_PASSWORD'
      - 'CHECKER_CONF=/checker.toml'
    volumes:
      - ./checker.toml:/checker.toml